### ISSUE TITLE
Blank Rows inserted in the COBie.xls export

### ISSUE THREAD

**Issue by billeast** [opensourceBIM/COBie-plugins#13]
In completing a COBie export on the new sample Dormitory project the export routine incorrectly included 47 additional rows of blank data. This could be seen by sorting the Type.Name column.

Please check all exports because it appears that incorrect rows are being inserted in most worksheets.

**Comment by OhmSweetOhm** [comment]
Fixed in the 1.4 branch, commit d015ef7
