### ISSUE TITLE
Error message on starting bimServer

### ISSUE THREAD

**Issue by billeast** [opensourceBIM/COBie-plugins#16]
I started working with the lastest bimServer and plugins on the new sample Dormitory project we're trying to release and the plugins looked like they where there and ran, but then nothing happened.  In reviewing the start-up logs there were errors in loading the plug ins. Please see the following error message:

[2016-01-16-ErrorMessages.txt](https://github.com/opensourceBIM/COBie-plugins/files/92947/2016-01-16-ErrorMessages.txt)

**Comment by billeast** [comment]
Note that this was on a PC running Windows 10. Java Version 8 Update 66 (build 1.8.0_66_b18)

**Comment by OhmSweetOhm** [comment]
Current build is only compatible with BIMServer v1.4.
