### ISSUE TITLE
Non-Printing ASCII Characters padding cells

### ISSUE THREAD

**Issue by billeast** [opensourceBIM/COBie-plugins#17]
All cells have added spaces. All values should be cleaned for XML-safe ASCII characters and left/right trimmed.

**Comment by billeast** [comment]
What I've needed to do to fix this is to save the exported file in a .xlsm (macro enabled spreadsheet). Put in the following macro:

Sub CleanUp()
    Dim cell As Range
        For Each cell In ActiveSheet.UsedRange.SpecialCells(xlCellTypeConstants)
        cell = WorksheetFunction.Trim(WorksheetFunction.Clean(cell))
    Next cell
End Sub

and run the macro on every sheet. I could have looped over each sheet, but better safe than sorry, so I did it on every sheet.

**Comment by OhmSweetOhm** [comment]
Fixed in Commit f5b6f65 for BIMServer 1.4 Branch.
