### ISSUE TITLE
COBie.Connection.RealizingElement

### ISSUE THREAD

**Issue by billeast** [opensourceBIM/COBie-plugins#21]
In one of the first tests of the COBie.Connection export (related to SPARKie testing). It has been noticed that COBie.Connection.RealizingElement throws an error on "n/a". This is not correct as their could be a direct (physical or logical) connection between upstream and downstream elements that does not require and additional "RealizingElement". Please loosen this restriction to be "n/a" or Component.Name or Type.Name.  Thanks!

**Comment by OhmSweetOhm** [comment]
Fixed in [Release1.1.4](https://github.com/opensourceBIM/COBie-plugins/releases/tag/1.1.4), commit d8739ce
