### ISSUE TITLE
COBie.Zone blank row error

### ISSUE THREAD

**Issue by billeast** [opensourceBIM/COBie-plugins#22]
In the command line tool, when checking zone, a blank row 2 in the file throws an error, instead of being ignored.

**Comment by OhmSweetOhm** [comment]
I haven't been able to replicate this error so far. Can you post a file - or send to me privately?

The attached file returns zero errors for zone and row 2 is blank.

[cobie_test2.xlsx](https://github.com/opensourceBIM/COBie-plugins/files/253038/cobie_test2.xlsx)

**Comment by billeast** [comment]
Files attached per request. This pertains to xlsx file checking so may apply to Command Line Tool only.

[EDORM-RevitCOBieExport - US3.zip](https://github.com/opensourceBIM/COBie-plugins/files/257518/EDORM-RevitCOBieExport.-.US3.zip)

**Comment by OhmSweetOhm** [comment]
Ahhh.  I see what's going on now.  You've got some blank spaces in Row 2 in the cells (most of them).  In any case, I should filter rows out if there is nothing in them after trimming leading and trailing space.

**Comment by OhmSweetOhm** [comment]
I just fixed it in my local copy.  A new release is forthcoming when I finish fixing one or two other issues.

**Comment by billeast** [comment]
I suspected non-printing ASCII characters.  How about just filtering all of these out?

**Comment by billeast** [comment]
Cool. Thanks! Keep those facebook posts coming! Love to see those happy kids!

**Comment by OhmSweetOhm** [comment]
Fixed in [Release1.1.4](https://github.com/opensourceBIM/COBie-plugins/releases/tag/1.1.4), commit d8739ce
