### ISSUE TITLE
IfcOrganization.Role not correctly placed within COBie.Contact.Category

### ISSUE THREAD

**Issue by billeast** [opensourceBIM/COBie-plugins#23]
In NBIMS-US V3, Annex A, Page 47. COBie.Contact.Category is mapped to: "Constructs a comma delimitted list of the unique strings found in IfcPersonAndOrganization.Roles, IfcPersonAndOrganization.ThePerson.Roles, and IfcPersonAndOrganization.TheOrganization.Roles"

In the example dormitory file I have:
#35= IFCTELECOMADDRESS($,$,$,$,$,$,('daniel@cadandesign.com'),$);
#39= IFCPERSON($,'','Daniel',$,$,$,$,(#35));
#43= IFCORGANIZATION($,'Cadan Design','34-20 11 00 Design Roles',$,$);
#44= IFCPERSONANDORGANIZATION(#39,#43,$);

The OmniClass code provided in #43 is placed in the exported COBie version of the IFC file as COBie.Contact.Department. That neither meets the mapping for COBie.Contact.Department specified on In NBIMS-US V3, Annex A, Page 47 nor the definition above. 

Recommend that we update the mapping and code to ensure that COBie.Contact.Catgory mapping also includes the ifcOrganization.Role.

**Comment by OhmSweetOhm** [comment]
In the noted example, "34-20 11 00 Design Roles'" is placed in the Description slot of IFCORGANIZATION.  The ROLES slot (4th) in the example is null. My suspicion is that there were some alternate processing rules in place to populate Department with the description field if the official source for Department was not available.  

I need to review the NBIMS document regarding Department, but the responibility matrix says it maps to IfcPostalAddress.InternalLocation.  Alternatively,if there are no IfcPostalAddresses with InternalLocation populated then the Organization.Relates collection is parsed and the last organization name is used.  If niether of those paths yield a result then the Company Name is repeated.  

In any case, it looks like the export code is not playing by the rules here and this will be fixed.

**Comment by OhmSweetOhm** [comment]
I investigated further...

There are a couple of issues:

1)  For IFC to COBie the Responsibility Matrix Says (for Department):  3If there are no IfcPostalAddresses with InternalLocation populated then the Organization.Relates collection is parsed and the last organization name is used.  If niether of those paths yield a result then the Company Name is repeated.

The code was doing all of that but as a final option it was using IfcOrganization.Description as a final option for Contact.Department.  I am commenting out that part of the code.  In the example provided, the OMNI class category is in the IfcOrganization.Description field and that is how it ended up in Department.

2)  In COBie to IFC code the IfcOrganization.Description was getting initialized to the Contact.Department value.

So combining 1 and 2 it is clear how that value would make round trips into and out of BIMServer in the way of COBie transforms.  

I'm looking at the original IFC file and it looks like that OMNI class code was put in the IfcOrganization.Description field in the Revit export...
43= IFCORGANIZATION($,'Cadan Design','34-20 11 00 Design Roles',$,$);

In any case, I'm getting rid of those extra processing bits to follow the standard more closely.

**Comment by OhmSweetOhm** [comment]
Fixed in [Release1.1.4](https://github.com/opensourceBIM/COBie-plugins/releases/tag/1.1.4), commit d8739ce
