### ISSUE TITLE
Type.WarrantyDurationUnit default

### ISSUE THREAD

**Issue by billeast** [opensourceBIM/COBie-plugins#26]
It appears if there is no value for WarrantyDurationUnit the default is being set to "SECONDS" instead of "n/a". This was encountered on a design COBie export file.  

test file is attached below:
[Dormitory-SECU-TEST.zip](https://github.com/opensourceBIM/COBie-plugins/files/657834/Dormitory-SECU-TEST.zip)

resulting XLSX file attached below:
[SECU-R2-T3.zip](https://github.com/opensourceBIM/COBie-plugins/files/657838/SECU-R2-T3.zip)

**Comment by OhmSweetOhm** [comment]
If the transform doesn't find a warranty duration unit then it is looking for the first time unit in the IfcProject.UnitsInContext property (i.e. the default time unit for the project).  While it's debatable whether or not the transform should behave that way in typical cases, it is clear that it should not provide a unit if there is no value for warranty.  It doesn't make sense to provide the default IfcProject units for warrantydurationunit if there is no warranty value for parts or labor.

**Comment by OhmSweetOhm** [comment]
Fixed in Release 1.1.6.0 and commit ade5ae606327888230510906c7d35b3620d251e1
