### ISSUE TITLE
AssetType property not being picked up

### ISSUE THREAD

**Issue by billeast** [opensourceBIM/COBie-plugins#27]
All Types have a property of "AssetType" in the attached file:
[Dormitory-SECU-TEST.zip](https://github.com/opensourceBIM/COBie-plugins/files/657852/Dormitory-SECU-TEST.zip)

the information is not showing up in the resulting XLSX file:
[SECU-R2-T3.zip](https://github.com/opensourceBIM/COBie-plugins/files/657853/SECU-R2-T3.zip)

**Comment by OhmSweetOhm** [comment]
Fixed in Release 1.1.6.0 and commit ade5ae606327888230510906c7d35b3620d251e1
