### ISSUE TITLE
Attribute.Description 

### ISSUE THREAD

**Issue by billeast** [opensourceBIM/COBie-plugins#30]
if there is no attribute.description, do not default attribute.description to attribute.name as there is no additional information provided by the duplication. suggest to use the default "n/a" or "$" depending on format.

**Comment by OhmSweetOhm** [comment]
We should use the "n/a" default to be consistent with everything else

**Comment by OhmSweetOhm** [comment]
Fixed in 1.1.6 and commit ade5ae606327888230510906c7d35b3620d251e1
