### ISSUE TITLE
Facility.CreatedBy

### ISSUE THREAD

**Issue by billeast** [opensourceBIM/COBie-plugins#31]
Facility.CreatedBy is actually exporting the Facility.Category

[ARC.xlsx](https://github.com/opensourceBIM/COBie-plugins/files/687765/ARC.xlsx)

**Comment by OhmSweetOhm** [comment]
Acknowledged.  I found a bug in the code for this and have fixed it in my local version.  Will post a fix soon.

**Comment by OhmSweetOhm** [comment]
Fixed in 1.1.6 and commit ade5ae606327888230510906c7d35b3620d251e1
