### ISSUE TITLE
Type, System, Attribute checking ignored in this test file?

### ISSUE THREAD

**Issue by billeast** [opensourceBIM/COBie-plugins#33]
For some reason entire tables are missing from review when the following file was run through the COBie Plugin for bimServer. We tried clean/trim on the individual rows but that's not working. Here are the files and the associated QC Report. 
[2017-03-28-Dormitory-SECU-v4.xlsx](https://github.com/opensourceBIM/COBie-plugins/files/890402/2017-03-28-Dormitory-SECU-v4.xlsx)
![qcreportexport](https://cloud.githubusercontent.com/assets/6697221/24614689/9541a5b8-1851-11e7-9fe2-f1c700962712.jpg)

**Comment by billeast** [comment]
Is there something wrong in the file provided with the encoding of the Tab name itself?

**Comment by billeast** [comment]
(oops closed by mistake).  Also note that these Tabs are correctly checked in the COBieQCReporter. I know that there has been some divergence in the code base between these two as we make improvements for classification and property checking, however, this is the first time this type of issue has occurred to my knowledge.

**Comment by OhmSweetOhm** [comment]
Checking it out now...

**Comment by OhmSweetOhm** [comment]
Note that those items are also not coming out on a COBie spreadsheet download.  i.e. they do not appear in a round trip.  This must be something related to the ifc to cobie transformation.  Looking further...

**Comment by OhmSweetOhm** [comment]
Here's what's going on...
On the import the Types are being populated as IfcTypeProduct.  That's the default IFC Type when the extObject field cannot be mapped to a specific Type - and the corresponding components are mapped to IfcFurnishingElement.  In the default Ifc to COBie config file, IfcTypeProduct Types are excluded from the COBie export.  Thus, they are not going to show up in the QC checks or the COBie files.  Here's how to resolve the issue...

1.  Stop BIMServer
2.  Backup the following file somewhere on your desktop (or some other personal directory):
<BIMSERVERINSTALLDIRECTORY>\home\CobiePlugins\config\IfcToCobieConfig.xml
3.  Open the following file in a text editor (I suggest Notepad++):
<BIMSERVERINSTALLDIRECTORY>\home\CobiePlugins\config\IfcToCobieConfig.xml
4.  Delete the element under IfcTypeExclusions that is: <Name>IfcTypeObject</Name>
5.  Save the file
6.  Restart BIMServer and try the export/QC report again

**Comment by DrShawnOKeeffe** [comment]
I followed the steps above and there is no difference in the COBie MVD.

There are 102 IFCFURNISHINGELEMENT's before and after fix in the post above and also 24 IFCTYPEPRODUCT's before and after.

The XLSX and the STEP file serialised by the BIMserver are attached.

Looking forward to moving this discussion further in the future.

Thanks.  :) 

[Archive.zip](https://github.com/opensourceBIM/COBie-plugins/files/1071893/Archive.zip)

**Comment by billeast** [comment]
A tool for correcting poorly created IFC Object Types (provided a proper OmniClass -or equivalent- classification is provided) is to be included in our new kickstarter. https://www.kickstarter.com/projects/181317229/cobie-toolbox
